pagopa/io-onboarding-pa-api

README.md, package.json, src/app.ts, src/index.ts, src/utils/logger.ts, yarn.lock
This pull request implements a basic express server connected to a local postgres db.
=> [#166791583] Implement an express server connecting to postgres db

package.json, src/app.ts, src/config.ts, src/types/PublicAdministration.ts, yarn.lock
This PR creates an endpoint to retrieve the list of Public Administrations whose names match the user input.
=> [#166728960] Add endpoint to search public administrations from IPA

src/app.ts
This PR aims to add a route to the root URL so that the requests on the root return a successful response instead of the express default error for not found pages.
=> [#168290126] Define route on the root url

src/app.ts, src/controllers/__tests__/authenticationController.test.ts, src/controllers/authenticationController.ts, src/services/__tests__/sessionStorage.test.ts, src/services/sessionStorage.ts
This PR aims to fix a bug in SPID login for new users: an error on the user save is currently returned from the backend, this PR fix the code in order to avoid that error and to perform a redirect to the proper client page if any error still occurs. The error log was missing, it has also been added.
=> [#168643765] Fix SPID login for new users

src/types/__tests__/user.test.ts, src/types/user.ts
This PR aims to add a check to the SPID authentication level in the response from the IdP in order to forbid the login with level 1.
=> [#168635195] Check SPID authentication level in IdP response

openapi.yml, src/app.ts
https://api.pa-onboarding.dev.io.italia.it## This PR
Uses link relations like
```
"links": {
"rel": "self",
"href": "https://api.pa-onboarding.dev.io.italia.it/public-administrations/c_e0956"
}
```
If you use `link` then use link-relations with a list
of entries. This enables sending different links and
guide the user-agent.
Use fqdn to avoid clients to maintain the state
b/w different requests.
=> If you use links, then use Link Relations.

openapi.yml, package.json, src/app.ts, src/controllers/__tests__/authenticationController.test.ts, src/controllers/__tests__/profileController.test.ts, src/controllers/organizationController.ts, src/controllers/profileController.ts, src/migrations/20190905174818-add-scope-column-to-organizations-table.ts, src/migrations/20191009145024-add-deletedat-column-to-organizations-users-table.ts, src/migrations/20191014124348-rename-column-firstname-of-users-table-into-givenname.ts, src/models/Organization.ts, src/models/OrganizationUser.ts, src/models/Session.ts, src/models/User.ts, src/services/__tests__/organizationService.test.ts, src/services/__tests__/profileService.test.ts, src/services/__tests__/sessionStorage.test.ts, src/services/organizationService.ts, src/services/profileService.ts, src/services/sessionStorage.ts, src/types/PublicAdministration.ts, src/types/__tests__/user.test.ts, src/types/organization.ts, src/types/user.ts, yarn.lock
This PR aims to create an endpoint that allows a delegate to register a public administration from iPA: the public administration and its legal representative are saved into the database and the associations between the organization and both the legal representative and the delegate are created.
=> [#168425079] Organization registration endpoint

openapi.yml, src/controllers/organizationController.ts
This PR aims to change the format of the public administration search response in order to comply with guideline [#110](https://opensource.zalando.com/restful-api-guidelines/#110).
=> [#169184063] Fix response data format of public administration search

openapi.yml
This PR aims to fix some errors in property names and schema definitions of OpenApi specs file
=> [#169359839] correct schema definitions in specs

.env, README.md, package.json, src/@types/nodemailer-mock-transport.d.ts, src/app.ts, src/controllers/__tests__/authenticationController.test.ts, src/controllers/__tests__/profileController.test.ts, src/controllers/profileController.ts, src/index.ts, src/locales/it.ts, src/migrations/20190905174818-add-scope-column-to-organizations-table.ts, src/services/__tests__/emailService.test.ts, src/services/__tests__/profileService.test.ts, src/services/emailService.ts, src/services/profileService.ts, src/types/__tests__/user.test.ts, src/types/user.ts, yarn.lock
This PR aims to add the logic to send a notification email on a successful update of the work email address.
=> [#169185738] Add email notification send on workEmail address change

package.json, yarn.lock
Test that requestBody works as expected in io-utils.
=> [#169314231] Reference updated package 4.1.1-beta.3

openapi.yml, src/controllers/__tests__/organizationController.test.ts, src/controllers/organizationController.ts, src/migrations/20191118142320-add-registration-status-column-to-organizations-table.ts, src/models/Organization.ts, src/services/__tests__/organizationService.test.ts, src/services/organizationService.ts, src/types/organization.ts
This PR aims to add the logic to delete the unconfirmed organizations that would cause a conflict when starting a new registration process
=> [#169810945] Unconfirmed registration deletion

openapi.yml
This PR aims to add the missing error responses to the OpenAPI specifications file.
=> [#169591795] Add specifications for missing error responses

package.json, src/acl/acl.ts, src/controllers/organizationController.ts, yarn.lock
This PR aims to add a role-based access control mechanism.
=> [#169971129] Integrate a role-based access control mechanism

.env.example, README.md, src/config.ts, src/services/organizationService.ts
This PR aims to add a limit to the number of administrations returned by a search.
=> [#169034086] Add a limit to the administration search results

openapi.yml, src/services/organizationService.ts
This PR aims to order alphabetically the results of the administration search.
=> [#168752299] Order by name the administration search results

openapi.yml, src/acl/acl.ts, src/app.ts, src/controllers/__tests__/organizationController.test.ts, src/controllers/organizationController.ts, src/services/__tests__/organizationService.test.ts, src/services/organizationService.ts, src/utils/responses.ts
This PR aims to create an endpoint that allows a user to become an additional delegate of a registered organization.
=> [#170045286] Create endpoint to add an additional delegate to an organization

.auto-changelog.json, .release-it.js, package.json, preview.hbs, yarn.lock
adds [release-it](https://github.com/release-it/release-it).
running `yarn release-it <minor|major|patch>` will generate changelog entries, bump version (use semver) in package.json, create a tag and the relative github release.
use the pattern "`BREAKING CHANGE:`" in your commit messages to communicate breaking changes.
=> [#170442913] add release-it

src/controllers/__tests__/organizationController.test.ts, src/controllers/__tests__/profileController.test.ts, src/index.ts, src/services/__tests__/emailService.test.ts, src/services/emailService.ts
fix: default from field belongs to the second parameter of `createTransport`
=> [#170377705] fixes default from field value

src/migrations/20200115170841-remove-user-role-column-from-organizations-users-table.ts, src/models/OrganizationUser.ts, src/services/__tests__/organizationService.test.ts
This PR aims to remove the unnecessary `userRole` column from the `OrganizationsUsers` table.
=> [#170578348] Remove userRole column from OrganizationsUsers table

src/acl/acl.ts, src/controllers/organizationController.ts
This PR aims to refactor the permissions on the `/request/actions` endpoint in order to make them consistent with the resources affected.
=> [#170598868] Refactor permissions on registration request actions

openapi.yml, src/app.ts, src/controllers/organizationController.ts
This PR aims to add the logic to distinguish the required action on a bulk of request before invoking the corresponding method to perform it.
=> [#170744609] Distinguish type of request action before performing it

src/app.ts, src/controllers/__tests__/requestController.test.ts, src/controllers/requestController.ts, src/locales/it.ts
This PR aims to rename the class `OrganizationController` into `RequestController`.
=> [#170596020] Rename class: OrganizationController -> RequestController

src/controllers/__tests__/requestController.test.ts, src/controllers/requestController.ts
This PR aims to add a test suite for the `handleAction()` method of the organization controller.
=> [#170596020] Implement test for request actions handler method

openapi.yml
Adds a link to the source code in documentation.
=> Add github url in documentation.
